### ISSUE TITLE
Add REST API

### ISSUE THREAD

**Issue by bonzini** [patchew-project/patchew#25]
This would make it possible to integrate Patchew with external applications, such as IFTTT's "Maker channel" or Jenkins.

Todo list:

- [x] basic read-only API
- [x] "Results" infrastructure
  - [x] separate endpoint for results (`/project/[id]/series/[msgid]/results`) instead of including them in the details view
  - [x] project results (`/project/{id}/results`)
  - [x] Refactor 'results' into a database table to allow posting arbitrary results via the REST API (see issue #73)
- [x] basic write support for series/messages (flags, reviewers, ...)
- [ ] add missing features of the old API
  - [x] importing from mailing lists (issue #75)
  - [x] tracking git repositories
  - [x] access test capabilities
  - [ ] `applier-get`, `tester-get`
  - [x] `applier-report`, `tester-report` (PUT of results, issue #82)
  - [x] access module config (subset of properties access in the old API, issue #112)
- [x] Token authentication

**Comment by bonzini** [comment]
Todo list:

- [ ] add missing features of the old API (importing from mailing lists, tracking git repositories)
- [ ] OAuth authentication
- [ ] Refactor 'results' into a database table to allow posting arbitrary results via the REST API

**Comment by bonzini** [comment]
Search on results is there, but applier-get and tester-get atomically change the result to pending too and do more updates. Ideas welcome on whether this should become a separate action, or whether PATCH could be used too...

**Comment by bonzini** [comment]
Applier-get and tester-get should be POST actions directly under `/api/v1/`.

**Comment by bonzini** [comment]
Posted support for token authentication.

**Comment by bonzini** [comment]
And everything that's missing is now available at [bonzini/patchew#rest-client](https://github.com/bonzini/patchew/tree/rest-client).

**Comment by bonzini** [comment]
Merged.
